[package]
name = "noise"
version = "0.1.0"
authors = ["Manu Mtz.-Almeida <manu.valladolid@gmail.com>"]
build = "build.rs" # LALRPOP preprocessing

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"
regex = "0.2.1"
